### ISSUE TITLE
What's your comments on the hypothesis about the distribution of travel supply and demand ?

### ISSUE THREAD

**Issue by colin-fox** [illidanlab/Simulator#11]
What are your comments on the hypothesis that takes the distribution of order's origin to imitate the distribution of travel demand event, and similarly takes the distribution of order's destination to imitate the distribution of travel supply event?

**Comment by KaixiangLin** [comment]
- For the demand side, I don't know a better way other than order origin to approximate demand.
- For the supply side, only counting order destination is not accurate since drivers can also become available at a location by either traveling to that location (without passengers) or simply becoming online.
