### ISSUE TITLE
What is the size of the inner diameter of your hexagonal cell?

### ISSUE THREAD

**Issue by colin-fox** [illidanlab/Simulator#9]
When building the hexagonal grid world, what is your consideration of the factors that determine the size of each grid?  what is the size of the inner diameter of the hexagonal grid used in your experiment?

**Comment by KaixiangLin** [comment]
The grid's size is 1.2 km, so that we can reasonably assume the driver can move from one grid to another within 10 mins. We discretize time into 10 mins intervals. Each step in the simulator corresponds to a 10 mins time interval. 
Please also refer to our [paper](https://dl.acm.org/doi/pdf/10.1145/3219819.3219993) Sec 6.3 on this.
